{{- if include "chart.localhost.hasTLS" . }}
{{- $tls := include "chart.localhost.tls" . | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: localhost-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.cert | b64enc }}
  tls.key: {{ $tls.key | b64enc }}
{{- end }}
